name: kylonas
favicon: null
layout_spectrum: 0.2736105564981699
typography_spectrum: 0.339852532139048
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e6e6e6'
    - '#7b005a'
    - '#fa6271'
    - '#b397b1'
    - '#5bb5b3'
  brandStrength: 0.4580926888156682
  lightness: 0.3499404122121632
  saturation: 0.36049502599053085
  rhythmicContrast: 0.7109953600447625
purpose: []
